#ifndef PEBBLEWEATHER_H
#define PEBBLEWEATHER_H

// unused
typedef enum {
#if 0
	W_ICON_CLEAR_DAY = 0,
	W_ICON_FAIR_DAY,
	W_ICON_PARTLY_CLOUDY_DAY,
	W_ICON_MOSTLY_CLOUDY_DAY,
	W_ICON_CLOUDY,
	W_ICON_CLEAR_NIGHT,
	W_ICON_FAIR_NIGHT,
	W_ICON_PARTLY_CLOUDY_NIGHT,
	W_ICON_WIND,
	W_ICON_FOG,
	W_ICON_DRIZZLE,
	W_ICON_RAIN,
	W_ICON_RAIN_SLEET,
	W_ICON_SLEET,
	W_ICON_SNOW_SLEET,
	W_ICON_HEAVY_SNOW,
	W_ICON_SNOW,
	W_ICON_RAIN_SNOW,
	W_ICON_RAIN_SUN,
	W_ICON_THUNDER_SUN,
	W_ICON_THUNDER,
	W_ICON_COLD,
	W_ICON_HOT,
	W_ICON_PHONE_ERROR,
	W_ICON_NOT_AVAILABLE,
	W_ICON_COUNT
#else
	W_ICON_COUNT = 5 * 5
#endif
} WeatherIcon;

enum {
	COMM_TYPE = 0,
	COMM_OFFSET = 1,
	COMM_DATA = 2,
};

enum {
	TYPE_FIRST_TIME = 0,
	TYPE_TEMPERATURE = 1,
	TYPE_PRECIPITATION = 2,
	TYPE_SKY = 3,
	TYPE_EOF = 4,
	TYPE_ERROR = 5,
	TYPE_DATA_COUNT = 6,
	TYPE_PRECIPITATION_SNOW = 7,
};

#endif // PEBBLEWEATHER_H
